### PR TITLE
fix update of staticAutocomplete when API or token is updated

### LINKED ISSUE #156: static autocomplete and coverage/api change
* API: https://api.navitia.io/v1
* add coverage key
* change API (for sncf for example)
* click on coverage value: the old list appear

### PR DESCRIPTION
**Pull request by TeXitoi**
fix #156

### CODE REVIEW

File: js/autocomplete.js [hunk 1]
```diff
@@ -113,19 +113,40 @@ var autocomplete = {
...
+                old_request = request;
+                old_token = token;
+                autocomplete.updateStaticAutocomplete(input, staticType, request, token);
+            } else if ($(input).is(':focus')) {
+                $(input).autocomplete('search', '');
+            }
+
+        };
+        handle();
+        $(input).focus(handle);
```
Comment (xlqian) [inline js/autocomplete.js]: L143 and L144 coexist?

Comment (TeXitoi) [inline js/autocomplete.js]: 143 is for the first time (for example at the page loading, or when adding the field), 144 is on the focus event.
