### PR TITLE
Jquery ui fixes

### LINKED ISSUE #152: Datetime graphics not working (see PNG attached)
navitia playground

Checked on Firefox/GoogleChrome and Internet Explorer

This is a test request working to check the case :
http://canaltp.github.io/navitia-playground/play.html?request=https%3A%2F%2Fapi.navitia.io%2Fv1%2Fcoverage%2Ffr-idf%2Fjourneys%3Ffrom%3D2.362292%253B48.876159%26to%3Dstop_area%253AOIF%253ASA%253A8738400%26datetime%3D20160627T080000%26datetime_represents%3Darrival%26first_section_mode%255B%255D%3Dbss%26first_section_mode%255B%255D%3Dbike%26forbidden_uris%255B%255D%3Dphysical_mode%253AMetro%26forbidden_uris%255B%255D%3Dphysical_mode%253ABus%26forbidden_uris%255B%255D%3Dphysical_mode%253ARapidTransit%26&token=fc4b8d9e-ca2e-487f-9c04-c81fc9d2a781

### PR DESCRIPTION
**Pull request by TeXitoi**
Force 1.11.4 as the autocomplete theme does not work with 1.12.0.

Theme datetime picker

fix #152 #94

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -64,19 +64,17 @@ gulp.task('prod:scripts', compile_js('prod'));
...
-            '**/renderjson.js',
-            '**/urijs/src/URI.js',
-            '**/jqueryui-timepicker-addon/dist/jquery-ui-timepicker-addon.js',
-            '**/sprintf/src/sprintf.js',
-            '**/leaflet/dist/leaflet-src.js',
-            '**/notifyjs/dist/notify.js',
-            '**/wkt2geojson/wkt2geojson.js',
-            '**/leaflet.label/leaflet.label.js',
-            '!**/*.min.js']))
+        return gulp.src([
```
Comment (xlqian) [inline gulpfile.js]: why?
